"use client";

import Image from "next/image";
import { ChangeEvent, CSSProperties, useCallback, useEffect, useMemo, useRef, useState } from "react";
import { CalendarDays, Camera, Check, ChevronLeft, ChevronRight, Dumbbell, FileUp, Flame, History, ImagePlus, Moon, Pause, Pencil, Play, Plus, RotateCcw, Save, SkipForward, Trash2 } from "lucide-react";
import { getCueMode, playCue } from "@/lib/client-cues";

type Tab = "today" | "plan" | "history" | "progress";
type Phase = "warm_up" | "exercise" | "stretching";
type Item = { id: string; phase: Phase; sort_order: number; exercise_name: string; sets: number | null; reps: number | null; weight_kg: number | null; duration_seconds: number | null; rest_seconds: number | null; sides: number | null; notes: string | null };
type Day = { id: string; date: string; day_type: "workout" | "rest"; title: string | null; notes: string | null };
type GymRow = { week_start: string; date: string; day_type: "workout" | "rest"; title: string | null; phase: Phase | null; order: number | null; exercise_name: string | null; sets: number | null; reps: number | null; weight_kg: number | null; duration_seconds: number | null; rest_seconds: number | null; sides: number | null; notes: string | null };
type HistoryDay = { date: string; day_type: "workout" | "rest"; title: string | null; started_at: string | null; completed_at: string | null };
type Photo = { id: string; week_start: string; note: string | null; byte_size: number; created_at: string };

function localIso(date = new Date()) { return new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Kolkata", year: "numeric", month: "2-digit", day: "2-digit" }).format(date); }
function prettyDate(iso: string) { return new Intl.DateTimeFormat("en-IN", { weekday: "long", day: "numeric", month: "long" }).format(new Date(`${iso}T12:00:00`)); }
function mondayOf(iso: string) { const date = new Date(`${iso}T12:00:00Z`); const day = date.getUTCDay(); date.setUTCDate(date.getUTCDate() - (day === 0 ? 6 : day - 1)); return date.toISOString().slice(0, 10); }
function phaseLabel(phase: Phase) { return phase === "warm_up" ? "Warm up" : phase === "exercise" ? "Exercises" : "Stretching"; }
function formatTimer(seconds: number) { return `${String(Math.floor(seconds / 60)).padStart(2, "0")}:${String(seconds % 60).padStart(2, "0")}`; }
const nullableNumber = (value: string) => value === "" ? null : Number(value);

export function GymPage({ initialTab = "today" }: { initialTab?: Tab }) {
  const [tab, setTab] = useState<Tab>(initialTab);
  return <div className="section-page gym-page"><div className="page-heading"><div><p className="eyebrow gym-color">Your session</p><h1>Gym</h1><p className="muted">Follow the plan. One movement at a time.</p></div><div className="heading-icon gym-tint"><Dumbbell/></div></div><div className="top-tabs gym-tabs"><button className={tab === "today" ? "active" : ""} onClick={() => setTab("today")}><Play/>Today</button><button className={tab === "plan" ? "active" : ""} onClick={() => setTab("plan")}><Pencil/>Week plan</button><button className={tab === "history" ? "active" : ""} onClick={() => setTab("history")}><History/>History</button><button className={tab === "progress" ? "active" : ""} onClick={() => setTab("progress")}><Camera/>Progress</button></div>{tab === "today" && <WorkoutRunner openPlan={() => setTab("plan")}/>} {tab === "plan" && <WeekPlanner/>} {tab === "history" && <GymHistory/>} {tab === "progress" && <ProgressPhotos/>}</div>;
}

function WorkoutRunner({ openPlan }: { openPlan(): void }) {
  const date = localIso(); const [day, setDay] = useState<Day | null>(null); const [items, setItems] = useState<Item[]>([]); const [progress, setProgress] = useState<Record<string, number>>({});
  const [sessionComplete, setSessionComplete] = useState(false); const [loading, setLoading] = useState(true); const [timerSeconds, setTimerSeconds] = useState(0); const [timerRunning, setTimerRunning] = useState(false); const [restSeconds, setRestSeconds] = useState<number | null>(null); const completingRef = useRef(false);
  const load = useCallback(async () => { const data = await fetch(`/api/gym?date=${date}`).then((response) => response.json()); const loadedItems = (data.items ?? []) as Item[]; const loadedProgress = Object.fromEntries((data.progress ?? []).map((row: { workout_item_id: string; completed_sets: number }) => [row.workout_item_id, row.completed_sets])) as Record<string, number>; const loadedCurrent = loadedItems.find((item) => (loadedProgress[item.id] ?? 0) < (item.sets ?? 1)); setDay(data.day); setItems(loadedItems); setSessionComplete(Boolean(data.session?.completed_at)); setProgress(loadedProgress); setTimerSeconds(loadedCurrent?.duration_seconds ?? 0); setTimerRunning(false); setLoading(false); }, [date]);
  useEffect(() => {
    let active = true;
    void fetch(`/api/gym?date=${date}`).then((response) => response.json()).then((data) => {
      if (!active) return;
      const loadedItems = (data.items ?? []) as Item[];
      const loadedProgress = Object.fromEntries((data.progress ?? []).map((row: { workout_item_id: string; completed_sets: number }) => [row.workout_item_id, row.completed_sets])) as Record<string, number>;
      const loadedCurrent = loadedItems.find((item) => (loadedProgress[item.id] ?? 0) < (item.sets ?? 1));
      setDay(data.day); setItems(loadedItems); setSessionComplete(Boolean(data.session?.completed_at)); setProgress(loadedProgress);
      setTimerSeconds(loadedCurrent?.duration_seconds ?? 0); setLoading(false);
    });
    return () => { active = false; };
  }, [date]);
  const currentIndex = items.findIndex((item) => (progress[item.id] ?? 0) < (item.sets ?? 1)); const current = currentIndex >= 0 ? items[currentIndex] : null;
  const patch = useCallback(async (payload: object) => fetch("/api/gym", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }), []);
  const completeSet = useCallback(async () => {
    if (!current || !day) return;
    const target = current.sets ?? 1; const completedSets = Math.min(target, (progress[current.id] ?? 0) + 1);
    setTimerRunning(false);
    setProgress((value) => ({ ...value, [current.id]: completedSets }));
    await patch({ day_id: day.id, item_id: current.id, completed_sets: completedSets });
    if (completedSets < target) { setTimerSeconds(current.duration_seconds ?? 0); if (current.rest_seconds) setRestSeconds(current.rest_seconds); }
    else setTimerSeconds(items[currentIndex + 1]?.duration_seconds ?? 0);
    const isLast = currentIndex === items.length - 1 && completedSets >= target;
    if (isLast) { await patch({ day_id: day.id, complete_day: true }); setSessionComplete(true); if (!current.duration_seconds) void getCueMode().then(playCue); }
  }, [current, currentIndex, day, items, patch, progress]);
  useEffect(() => {
    if (!timerRunning || timerSeconds <= 0) return;
    const id = window.setTimeout(() => {
      const next = timerSeconds - 1; setTimerSeconds(next);
      if (next === 0 && !completingRef.current) { completingRef.current = true; setTimerRunning(false); void getCueMode().then(playCue).then(completeSet).finally(() => { completingRef.current = false; }); }
    }, 1000);
    return () => window.clearTimeout(id);
  }, [completeSet, timerRunning, timerSeconds]);
  useEffect(() => {
    if (restSeconds === null || restSeconds <= 0) return;
    const id = window.setTimeout(() => { const next = restSeconds - 1; if (next === 0) { setRestSeconds(null); void getCueMode().then(playCue); } else setRestSeconds(next); }, 1000);
    return () => window.clearTimeout(id);
  }, [restSeconds]);
  async function completeRest() { if (!day) return; await patch({ day_id: day.id, complete_day: true }); setSessionComplete(true); void getCueMode().then(playCue); }
  if (loading) return <section className="runner-card empty-state">Loading today’s workout…</section>;
  if (!day) return <section className="runner-card empty-state"><div className="empty-icon gym-tint"><FileUp/></div><h2>No workout plan for today</h2><p>Upload this week’s CSV, preview it, and save it first.</p><button className="primary-button gym-action" onClick={openPlan}>Open week plan</button></section>;
  if (sessionComplete) return <section className="runner-card workout-done"><div className="done-flame"><Flame/></div><p className="eyebrow">Session complete</p><h2>{day.title || "Workout done"}</h2><p>Everything planned for {prettyDate(date)} is complete.</p><button className="secondary-button" onClick={load}><RotateCcw/>Review session</button></section>;
  if (day.day_type === "rest") return <section className="runner-card rest-card"><div className="rest-moon"><Moon/></div><p className="eyebrow">Rest day</p><h2>{day.title || "Recovery is the plan"}</h2><p>{day.notes || "Nothing to chase today. Recover and come back ready."}</p><button className="primary-button rest-action" onClick={completeRest}><Check/>Complete rest check-in</button></section>;
  if (!current) return <section className="runner-card empty-state"><h2>This workout has no exercises</h2><button className="secondary-button" onClick={openPlan}>Edit week plan</button></section>;
  const completed = progress[current.id] ?? 0; const target = current.sets ?? 1; const phaseItems = items.filter((item) => item.phase === current.phase); const phaseDone = phaseItems.filter((item) => (progress[item.id] ?? 0) >= (item.sets ?? 1)).length; const timerTotal = current.duration_seconds ?? 1; const timerProgress = current.duration_seconds ? 1 - timerSeconds / timerTotal : completed / target;
  return <><section className="phase-strip">{(["warm_up", "exercise", "stretching"] as Phase[]).map((phase) => { const phaseList = items.filter((item) => item.phase === phase); const done = phaseList.length > 0 && phaseList.every((item) => (progress[item.id] ?? 0) >= (item.sets ?? 1)); return <div key={phase} className={`${phase === current.phase ? "active" : ""} ${done ? "done" : ""}`}><span>{done ? <Check/> : phaseLabel(phase).charAt(0)}</span><small>{phaseLabel(phase)}</small></div>; })}</section><section className="runner-card active-runner"><div className="runner-top"><div><p className="eyebrow">{phaseLabel(current.phase)} · {phaseDone + 1} of {phaseItems.length}</p><h2>{current.exercise_name}</h2></div><span className="set-pill">Set {Math.min(completed + 1, target)} / {target}</span></div><div className="prescription">{current.sets && <span>{current.sets} sets</span>}{current.reps && <span>{current.reps} reps</span>}{current.weight_kg !== null && <span>{current.weight_kg} kg</span>}{current.duration_seconds && <span>{current.duration_seconds}s</span>}{current.sides && <span>{current.sides} sides</span>}</div>{current.notes && <p className="movement-note">{current.notes}</p>}<div className="timer-ring" style={{ "--timer-progress": `${timerProgress * 360}deg` } as CSSProperties}><div>{current.duration_seconds ? <><strong>{formatTimer(timerSeconds)}</strong><small>{timerRunning ? "In progress" : "Ready"}</small></> : <><strong>{completed}</strong><small>sets complete</small></>}</div></div>{current.duration_seconds ? <button className="primary-button gym-action runner-main" onClick={() => setTimerRunning((value) => !value)}>{timerRunning ? <><Pause/>Pause</> : <><Play/>{timerSeconds === current.duration_seconds ? "Start timer" : "Resume"}</>}</button> : <button className="primary-button gym-action runner-main" onClick={completeSet}><Check/>Complete set {completed + 1}</button>}<div className="runner-secondary"><button className="text-button" onClick={() => { setTimerRunning(false); setTimerSeconds(current.duration_seconds ?? 0); }}><RotateCcw/>Reset</button><button className="text-button" onClick={completeSet}><SkipForward/>Skip / mark done</button></div>{items[currentIndex + 1] && <div className="up-next"><span>Up next</span><strong>{items[currentIndex + 1].exercise_name}</strong></div>}</section>{restSeconds !== null && <div className="rest-overlay"><section><p className="eyebrow">Rest between sets</p><strong>{formatTimer(restSeconds)}</strong><button className="secondary-button" onClick={() => setRestSeconds(null)}>Skip rest</button></section></div>}</>;
}

function WeekPlanner() {
  const today = localIso(); const [weekDate, setWeekDate] = useState(today); const [rows, setRows] = useState<GymRow[]>([]); const [errors, setErrors] = useState<string[]>([]); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const fileRef = useRef<HTMLInputElement>(null);
  async function loadWeek() { setBusy(true); const data = await fetch(`/api/gym?view=week&date=${weekDate}`).then((response) => response.json()); setRows(data.rows ?? []); setMessage(data.rows?.length ? "Saved week loaded. You can edit any field." : "No saved plan for this week."); setBusy(false); }
  async function upload(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; const form = new FormData(); form.append("file", file); const response = await fetch("/api/gym/preview", { method: "POST", body: form }); const data = await response.json(); setErrors(data.errors ?? (data.error ? [data.error] : [])); if (data.rows?.length) { setRows(data.rows); setWeekDate(data.rows[0].week_start); setMessage("Preview ready. Edit anything below, then save the week."); } event.target.value = ""; }
  async function save() { setBusy(true); setErrors([]); const response = await fetch("/api/gym", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ rows }) }); const data = await response.json(); if (response.ok) setMessage("Week saved. Today’s runner is ready."); else setErrors([data.error || "Could not save week."]); setBusy(false); }
  function patch(index: number, value: Partial<GymRow>) { setRows((current) => current.map((row, i) => i === index ? { ...row, ...value } : row)); }
  const start = rows[0]?.week_start ?? mondayOf(weekDate);
  function addRow(dayType: "workout" | "rest") { setRows((current) => [...current, { week_start: start, date: start, day_type: dayType, title: dayType === "rest" ? "Recovery" : "Workout", phase: dayType === "rest" ? null : "exercise", order: dayType === "rest" ? null : 1, exercise_name: dayType === "rest" ? null : "", sets: null, reps: dayType === "rest" ? null : 1, weight_kg: null, duration_seconds: null, rest_seconds: null, sides: null, notes: null }]); }
  return <section className="planner-card"><div className="planner-intro"><div><p className="eyebrow">Monday to Sunday</p><h2>Weekly plan</h2><p>Upload once, preview every row, edit now or come back later.</p></div><button className="primary-button gym-action" onClick={() => fileRef.current?.click()}><FileUp/>Upload CSV</button><input ref={fileRef} hidden type="file" accept=".csv,text/csv" onChange={upload}/></div><div className="load-week"><label>Week containing<input type="date" value={weekDate} onChange={(event) => setWeekDate(event.target.value)}/></label><button className="secondary-button" onClick={loadWeek} disabled={busy}><CalendarDays/>Load saved week</button></div>{message && <p className="status-message">{message}</p>}{errors.length > 0 && <div className="error-list">{errors.map((error) => <p key={error}>{error}</p>)}</div>}{rows.length > 0 ? <div className="gym-row-list">{rows.map((row, index) => <WorkoutRowEditor key={index} row={row} index={index} patch={patch} remove={() => setRows((current) => current.filter((_, i) => i !== index))}/>)}</div> : <div className="empty-state compact-empty"><FileUp/><h3>Your CSV preview appears here</h3><p>Use the example in <code>docs/CSV_SCHEMA.md</code>.</p></div>}<div className="planner-footer"><div><button className="add-row-button" onClick={() => addRow("workout")}><Plus/>Workout row</button><button className="add-row-button" onClick={() => addRow("rest")}><Moon/>Rest day</button></div>{rows.length > 0 && <button className="primary-button gym-action" onClick={save} disabled={busy || errors.length > 0}><Save/>{busy ? "Saving…" : "Save week"}</button>}</div></section>;
}

function WorkoutRowEditor({ row, index, patch, remove }: { row: GymRow; index: number; patch(index: number, value: Partial<GymRow>): void; remove(): void }) {
  const number = (key: keyof GymRow, value: string) => patch(index, { [key]: nullableNumber(value) } as Partial<GymRow>);
  return <article className={`workout-row-editor ${row.day_type}`}><div className="workout-row-head"><span className="editor-number">{index + 1}</span><input type="date" value={row.date} onChange={(event) => patch(index, { date: event.target.value })}/><select value={row.day_type} onChange={(event) => { const rest = event.target.value === "rest"; patch(index, { day_type: rest ? "rest" : "workout", phase: rest ? null : "exercise", exercise_name: rest ? null : row.exercise_name || "", order: rest ? null : row.order || 1 }); }}><option value="workout">Workout</option><option value="rest">Rest</option></select><button className="icon-button danger" onClick={remove}><Trash2/></button></div><input value={row.title ?? ""} onChange={(event) => patch(index, { title: event.target.value || null })} placeholder="Day title"/>{row.day_type === "workout" ? <><div className="field-grid three"><label>Phase<select value={row.phase ?? "exercise"} onChange={(event) => patch(index, { phase: event.target.value as Phase })}><option value="warm_up">Warm up</option><option value="exercise">Exercise</option><option value="stretching">Stretching</option></select></label><label>Order<input type="number" min="1" value={row.order ?? ""} onChange={(event) => number("order", event.target.value)}/></label><label>Exercise<input value={row.exercise_name ?? ""} onChange={(event) => patch(index, { exercise_name: event.target.value || null })}/></label></div><div className="metric-grid"><label>Sets<input type="number" min="1" value={row.sets ?? ""} onChange={(event) => number("sets", event.target.value)}/></label><label>Reps<input type="number" min="1" value={row.reps ?? ""} onChange={(event) => number("reps", event.target.value)}/></label><label>Weight kg<input type="number" min="0" step="0.25" value={row.weight_kg ?? ""} onChange={(event) => number("weight_kg", event.target.value)}/></label><label>Timer sec<input type="number" min="1" value={row.duration_seconds ?? ""} onChange={(event) => number("duration_seconds", event.target.value)}/></label><label>Rest sec<input type="number" min="0" value={row.rest_seconds ?? ""} onChange={(event) => number("rest_seconds", event.target.value)}/></label><label>Sides<input type="number" min="1" value={row.sides ?? ""} onChange={(event) => number("sides", event.target.value)}/></label></div></> : null}<input value={row.notes ?? ""} onChange={(event) => patch(index, { notes: event.target.value || null })} placeholder={row.day_type === "rest" ? "Recovery note (optional)" : "Technique note (optional)"}/></article>;
}

function GymHistory() {
  const today = localIso(); const [month, setMonth] = useState(today.slice(0, 7)); const [history, setHistory] = useState<HistoryDay[]>([]);
  useEffect(() => { fetch(`/api/gym?month=${month}`).then((response) => response.json()).then((data) => setHistory(data.history ?? [])); }, [month]);
  const map = useMemo(() => new Map(history.map((day) => [day.date, day])), [history]); const [year, monthNumber] = month.split("-").map(Number); const count = new Date(Date.UTC(year, monthNumber, 0)).getUTCDate(); const offset = (new Date(Date.UTC(year, monthNumber - 1, 1)).getUTCDay() + 6) % 7;
  function shift(value: number) { setMonth(new Date(Date.UTC(year, monthNumber - 1 + value, 1)).toISOString().slice(0, 7)); }
  return <section className="history-card"><div className="history-heading"><button className="icon-button" onClick={() => shift(-1)}><ChevronLeft/></button><div><p className="eyebrow">Gym history</p><h2>{new Intl.DateTimeFormat("en-IN", { month: "long", year: "numeric" }).format(new Date(Date.UTC(year, monthNumber - 1, 1)))}</h2></div><button className="icon-button" onClick={() => shift(1)}><ChevronRight/></button></div><div className="calendar-weekdays">{["M", "T", "W", "T", "F", "S", "S"].map((day, index) => <span key={`${day}-${index}`}>{day}</span>)}</div><div className="calendar-grid gym-calendar">{Array.from({ length: offset }).map((_, index) => <span key={`blank-${index}`}/>)}{Array.from({ length: count }, (_, index) => { const value = index + 1; const iso = `${month}-${String(value).padStart(2, "0")}`; const day = map.get(iso); const complete = Boolean(day?.completed_at); return <div key={iso} className={`${day ? "planned" : ""} ${complete ? "done" : ""} ${day?.day_type === "rest" ? "rest" : ""}`} title={day ? `${day.title || day.day_type}: ${complete ? "complete" : "not complete"}` : iso}><span>{value}</span>{complete && day?.day_type === "workout" ? <Flame/> : day?.day_type === "rest" ? <Moon/> : null}</div>; })}</div><div className="legend"><span><i className="legend-box complete"/>Workout complete</span><span><i className="legend-box rest"/>Rest day</span><span><i className="legend-box planned"/>Planned</span></div><div className="history-list">{history.length ? [...history].reverse().map((day) => <div key={day.date}><span>{prettyDate(day.date)} · {day.title || day.day_type}</span><strong>{day.completed_at ? day.day_type === "workout" ? "🔥 Done" : "Rest checked" : "Not complete"}</strong></div>) : <p className="empty-copy">Upload a week and your sessions will appear here.</p>}</div></section>;
}

function ProgressPhotos() {
  const [photos, setPhotos] = useState<Photo[]>([]); const [weekStart, setWeekStart] = useState(mondayOf(localIso())); const [note, setNote] = useState(""); const [file, setFile] = useState<File | null>(null); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const load = useCallback(() => fetch("/api/gym/photos").then((response) => response.json()).then((data) => setPhotos(data.photos ?? [])), []);
  useEffect(() => { void load(); }, [load]);
  async function compress(input: File) { const bitmap = await createImageBitmap(input); const scale = Math.min(1, 1280 / Math.max(bitmap.width, bitmap.height)); const canvas = document.createElement("canvas"); canvas.width = Math.round(bitmap.width * scale); canvas.height = Math.round(bitmap.height * scale); canvas.getContext("2d")!.drawImage(bitmap, 0, 0, canvas.width, canvas.height); const blob = await new Promise<Blob | null>((resolve) => canvas.toBlob(resolve, "image/webp", 0.78)); if (!blob) throw new Error("Could not prepare the image."); return new File([blob], "progress.webp", { type: "image/webp" }); }
  async function upload() { if (!file) return; setBusy(true); setMessage(""); try { const prepared = await compress(file); if (prepared.size > 2_097_152) throw new Error("The compressed image is still above 2 MB. Choose a smaller photo."); const form = new FormData(); form.append("photo", prepared); form.append("week_start", weekStart); form.append("note", note); const response = await fetch("/api/gym/photos", { method: "POST", body: form }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setFile(null); setNote(""); setMessage("Weekly progress photo saved."); await load(); } catch (error) { setMessage((error as Error).message); } finally { setBusy(false); } }
  return <section className="progress-section"><div className="photo-upload-card"><div className="heading-icon gym-tint"><ImagePlus/></div><div><p className="eyebrow">One photo each week</p><h2>Track visible progress</h2><p>Your photo is compressed on this phone and stored directly in Postgres—no Cloudinary.</p></div><label>Week starting<input type="date" value={weekStart} onChange={(event) => setWeekStart(mondayOf(event.target.value))}/></label><label className="photo-drop"><ImagePlus/><span>{file ? file.name : "Choose a progress photo"}</span><small>JPEG, PNG or WebP · compressed below 2 MB</small><input hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => setFile(event.target.files?.[0] ?? null)}/></label><input value={note} onChange={(event) => setNote(event.target.value)} placeholder="Optional note: weight, energy, consistency…"/><button className="primary-button gym-action" disabled={!file || busy} onClick={upload}>{busy ? "Compressing…" : <><Camera/>Save weekly photo</>}</button>{message && <p className="status-message">{message}</p>}</div><div className="photo-grid">{photos.map((photo) => <article key={photo.id}><div className="photo-frame"><Image src={`/api/gym/photos/${photo.id}`} alt={`Progress for week of ${photo.week_start}`} fill sizes="(max-width: 700px) 50vw, 260px" unoptimized/></div><p>{new Intl.DateTimeFormat("en-IN", { day: "numeric", month: "short", year: "numeric" }).format(new Date(`${photo.week_start}T12:00:00`))}</p>{photo.note && <small>{photo.note}</small>}</article>)}{!photos.length && <div className="empty-state"><Camera/><h3>No progress photos yet</h3><p>Add only one per week. Re-uploading the same week replaces it.</p></div>}</div></section>;
}
